desc 'Generate Graphviz object graph'
task :garden => :yard do
  sh 'yard graph --full --dependencies --dot="-Tpng:quartz" -f docs/images/AX.dot'
end

desc 'Remove files generated by YARD'
task :clobber_yard do
  rm_rf '.yardoc/'
end
task :clobber => :clobber_yard

